version: '3.9'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      # - "4571:4571"
      # - "8080:8080"
    environment:
      - SERVICES=s3,lambda,apigateway,logs #s3
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
      - USER=root
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=info
    volumes:
      - ./localstack:/tmp/localstack
    networks:
      default:
      app_network:

  # # awscli
  # awscli:
  #   container_name: awscli
  #   image: amazon/aws-cli:latest
  #   environment:
  #     - AWS_DEFAULT_REGION=ap-northeast-1
  #     - AWS_DEFAULT_OUTPUT=json
  #     - AWS_ACCESS_KEY_ID=dummy
  #     - AWS_SECRET_ACCESS_KEY=dummy
  #   depends_on:
  #     - localstack
  #   entrypoint: aws --endpoint-url=http://localstack:4566 s3 mb s3://develop
  #   extra_hosts:
  #     - "localstack:172.16.238.1"
  #     - "develop.localstack:172.16.238.1"
  #   networks:
  #     default:
  #     app_network:

volumes:
  localstack:

networks:
  app_network:
    external: true